# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

#Leverage a bash command
- task: CmdLine@2
  inputs:
    script: env | sort
    #curl -X POST "https://$USERNAME:$PASSWORD@$URL"
  env:
    USERNAME: $(username)
    PASSWORD: $(password)
    URL: $(url)
    TEST: $(test)


- powershell: |
    # Using an input-macro:
    Write-Host "This works: $(mySecret)"

    # Using the env var directly:
    Write-Host "This does not work: $env:MYSECRET"

    # Using the mapped env var:
    Write-Host "This works: $env:MY_MAPPED_ENV_VAR"    # Recommended
  env:
    MY_MAPPED_ENV_VAR: $(mySecret)