# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

#Leverage a bash command
- task: CmdLine@2
  inputs:
    script: 'curl --data "host_config_key=$(HOST_CONFIG_KEY)" $(url) -k'
