---
- name: Install RHEL Repos and Packages
  hosts: web
  become: yes
  tasks:
    - name: install epel-release
      ansible.builtin.yum:
        name: epel-release
        state: latest

    - name: Install a list of packages with a list variable
      ansible.builtin.yum:
        name: "{{ packages }}"
      vars:
        packages:
        - httpd
        - httpd-tools
